"""
Create all plots at once
"""
import plot_figure_1_absorption_spectra
import plot_figure_2_richness
import plot_figure_3_EF
import plot_figure_4_traits_NFD_barplot

import plot_figure_S1_I_out
import plot_figure_S2_complementarity
import plot_figure_S3_NFD_individually